Disable and deliberately fail current tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,6 +14,8 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v2
+      - name: Fail the action so we wont be able to merge it
+        run: exit 1
       - name: Setup environments
         run: |
           ./.github/scripts/ci-checkout.sh
@@ -33,49 +35,49 @@ jobs:
       - name: Style checks
         run: ./.github/scripts/ci-style.sh
 
-  test-weak-ref:
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v2
-      - name: Setup environments
-        run: |
-          ./.github/scripts/ci-checkout.sh
-          ./.github/scripts/ci-setup.sh
+  # test-weak-ref:
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Setup environments
+  #       run: |
+  #         ./.github/scripts/ci-checkout.sh
+  #         ./.github/scripts/ci-setup.sh
 
-      # Run the tests
-      - name: DaCapo Tests with weak reference processing
-        run: |
-          ./.github/scripts/ci-build.sh
-          ./.github/scripts/ci-test-only-weak-ref.sh
+  #     # Run the tests
+  #     - name: DaCapo Tests with weak reference processing
+  #       run: |
+  #         ./.github/scripts/ci-build.sh
+  #         ./.github/scripts/ci-test-only-weak-ref.sh
 
-  test-assertions:
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v2
-      - name: Setup Environments
-        run: |
-            ./.github/scripts/ci-checkout.sh
-            ./.github/scripts/ci-setup.sh
+  # test-assertions:
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Setup Environments
+  #       run: |
+  #           ./.github/scripts/ci-checkout.sh
+  #           ./.github/scripts/ci-setup.sh
 
-      # Run the tests with assertions
-      - name: DaCapo Test (with extreme_assertions)
-        run: ./.github/scripts/ci-test-assertions.sh
+  #     # Run the tests with assertions
+  #     - name: DaCapo Test (with extreme_assertions)
+  #       run: ./.github/scripts/ci-test-assertions.sh
 
-  msrv:
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v2
-      - name: Install Rust toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          override: true
-      - name: Install cargo-msrv
-        run: cargo install cargo-msrv
-      # Verify the MSRV defined in Cargo.toml
-      - name: Verify MSRV
-        run: cargo msrv --path mmtk verify
-      # If the previous step fails, find MSRV
-      - name: Find MSRV
-        if: failure()
-        run: cargo msrv --path mmtk
+  # msrv:
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Install Rust toolchain
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #         override: true
+  #     - name: Install cargo-msrv
+  #       run: cargo install cargo-msrv
+  #     # Verify the MSRV defined in Cargo.toml
+  #     - name: Verify MSRV
+  #       run: cargo msrv --path mmtk verify
+  #     # If the previous step fails, find MSRV
+  #     - name: Find MSRV
+  #       if: failure()
+  #       run: cargo msrv --path mmtk
